import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SessionProvider from '@/lib/provider/SessionProvider';
import ThemeSwitcher from '@/components/ThemeSwitcher';
import Logo from '@/components/Logo';
import DesignerContextProvider from '@/components/context/DesignerContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <DesignerContextProvider>
              <div className='flex max-h-screen min-h-screen min-w-full flex-col bg-background'>
                <nav className='flex h-[60px] items-center justify-between border-b border-border px-4 py-2'>
                  <Logo />
                  <div className='flex items-center gap-4'>
                    <ThemeSwitcher />
                  </div>
                </nav>
                {children}
                <Toaster />
              </div>
            </DesignerContextProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
